apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ks1th6dxf-dotnet-basic
  janus-idp.io/tekton: ks1th6dxf-dotnet-basic
  backstage.io/kubernetes-id: ks1th6dxf-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ks1th6dxf-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
